"""
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
"""
import math


def triangle_gen():
    i = 1
    num = 1
    while True:
        yield num
        i += 1
        num += i


def divisor_gen(n):
    divisors = []
    for i in range(1, int(math.sqrt(n)+1)):
        if n % i == 0:
            yield i
            if i*i != n:
                divisors.append(n/i)
    for j in reversed(divisors):
        yield j


def main():
    tri_gen = triangle_gen()
    while True:
        num = next(tri_gen)
        print(num)
        if len(list(divisor_gen(num))) > 500:
            print(num)
            break







if __name__ == "__main__":
    main()